### ISSUE TITLE
[ap,android] revamp AP functionality on android side

### ISSUE THREAD

**Issue by daadu** [alternadom/WiFiFlutter#114]
Due to the deprecation of Android API, need to add new APIs wherever possible. This is change should be backward compatible, ie it should work with old devices as it is without any change required from the user.

## Related Issues
- Android 10 can't acces to /proc/net/arp: open failed: EACCES (Permission denied) #73
- WiFi AP not working #74
- doesnt work on android versions 8 and above #78 
- Wi-Fi disable is not working #82
- App crashed when try to connect to AP #94
- setWiFiAPEnabled fails on Android 10 #103
- java.lang.reflect.InvocationTargetException #117

#### Methods that will require re-work to support post Android O (SDK 26)
- `getWiFiAPSSID()` - get "random SSID" generated for `LocalOnlyHostspot`
- `getWiFiAPPreSharedKey()` - get "random pre shared key" generated for `LocalOnlyHostspot`
- `isWiFiAPEnabled()` - check if `LocalOnlyHostspot` hotspot is created
- `setWiFiAPEnabled(bool state)` - start/close hotspot with `LocalOnlyHostspot` API 

#### Methods that will be deprecated post Android O (SDK 26)
- `getClientList(bool onlyReachables, int reachableTimeout)`
- `getWiFiAPState()`
- `isWiFiAPSSIDHidden()`
- `setWiFiAPConfiguration(Object poWiFiConfig)`
- `setWiFiAPPreSharedKey(String psPreSharedKey)`
- `setWiFiAPSSID(String psSSID)`
- `setWiFiAPSSIDHidden(bool hidden)`

#### Methods that will work post Android O (SDK 26) with no changes
- `showWritePermissionSettings(bool force)`

### Notes
- https://stackoverflow.com/questions/47700717/change-wifi-hotspots-ssid-and-password-in-android-oreo-8-x

**Comment by fedepell** [comment]
Good idea to open an issue to follow this big topic. There are a few other issues (ie. #103, #82, #78) that are covered by this.

I'd find interesting contributing to this, but I'm somehow afraid that a big showstopper is that recent Android versions cripple a lot what an app can do as AP. For example one cannot configure AP SSID/Password (although could read it after it is created). Also just local (as without internet) AP seem to be possible (which, from the IoT point of view, could be fine).

Looking at the main page table I'd say (please correct me if I'm wrong or let's discuss):
- Get status of AP: the details that `getWifiApState` was returning seem will not be available in new API. We could listen to LocalOnlyHotspot maybe for some notifications but not really same. But probably we can at least say if it's enabled or not.
- Enabling/disabing access point: we can just request a `LocalOnlyHotspot`. This will open an AP without internet and with a randoly generated SSID/pass. Besides, this can be shared with other apps (so when you ask to activate/deactivate it depends also on the status of other apps, you are not the only one deciding)
- Getting / settings AP credentials: getting yes (of course always of the local), setting no.
- Enabling / disabling visibility: no
- Getting client list: wow current implementation is very low level! ;-) No idea if that could still work (surprised if it ever).
- Mac filtering: would say no

So while implementing what possible could be  _something_, my feeling is that it would be very crippled compared to the previous support. Especially not being able to set the SSID/Password (which needs therefore be always then re-inserted in devices that would use it) sounds to me like a showstopper :(

What do you think?

**Comment by daadu** [comment]
@fedepell I have enlisted most AP related issues here, can you make a plan to implement it?

**Comment by fedepell** [comment]
@daadu: Please check my comment above! I think the same features as we have now (but not supported for android 8 or above) are technically now impossible (ie. you cannot create a fully configured AP, you may only have the `LocalOnlyHotspot` for which you cannot set SSID/pass, which is rather different). 
So apart for of course adding a valid error to what is currently failing badly with exceptions, I think we should discuss if it is even worth or not implementing the other ones. Again for example I am not sure a `LocalOnlyHotspot` in a IoT environment makes any sense, as the IoT devices would need to have the SSID/pass reconfigured at every execution. So is it even worth implementing this?

**Comment by daadu** [comment]
@fedepell I have enlisted all "AP related" methods in `WifiForIotPlugin` (let me know if I missed any), Can you segregate them based on whether should be deprecated (not supported for >= Android SDK 26, will show proper error message and changes in Readme) or require re-work (will work with Android SDK 26 and greater, with some caveats, which will be mentioned in README)

**Comment by daadu** [comment]
This will give us idea of what needs to be done.

Regarding `LocalOnlyHotspot` - if that is the only option then we should implement it with proper warning message (as we have done for Wifi methods).

**Comment by daadu** [comment]
if the plugin is cripple(just with `LocalOnlyHostspot`) so be it, we will add proper warnings in README, and depreciation warning messages for those methods on `WifiForIoTPlugin` (maybe remove them completely in future, since, iOS part of the plugin does not support AP anyways)

**Comment by fedepell** [comment]
I cannot edit directly the description, but as far as I researched here is the status:

-  getClientList(bool onlyReachables, int reachableTimeout): not possible to implement (was a very low level hack, surprised it even worked ;-) )
-  getWiFiAPPreSharedKey(): not possible for the "normal" AP. only for `LocalOnlyHotspot` if implemented
-  getWiFiAPSSID(): not possible for the "normal" AP. only for `LocalOnlyHotspot` if implemented
-  getWiFiAPState(): not possible at least in details as before. We can only say for `LocalOnlyHotspot` if available, but not with previous states details
-  isWiFiAPEnabled(): not for the "normal" AP. only for `LocalOnlyHotspot` if implemented
-  isWiFiAPSSIDHidden(): not possible to implement
-  setWiFiAPConfiguration(Object poWiFiConfig): not possible to implement (note: `LocalOnlyHotspot` will automatically generate a random SSID/PSK configuration)
-  setWiFiAPEnabled(bool state): not possible for "normal" AP, we can only request `LocalOnlyHotspot`
-  setWiFiAPPreSharedKey(String psPreSharedKey): not possible to implement
-  setWiFiAPSSID(String psSSID): not possible to implement
-  setWiFiAPSSIDHidden(bool hidden): not possible to implement
-  showWritePermissionSettings(bool force): should already work now

Now in detail `LocalOnlyHotspot` basically is a configuration that gets a randomly generated SSID/PSK so you cannot somehow preconfigure IoT devices to use it, but you should configure them every time. This makes it IMHO quite useless, or at least for my use case (where the IoT devices cannot be easily reconfigured, as they don't have an easily reachable UI / configuration)
Additionally `LocalOnlyHotspot`, as the name suggests, cannot share connection to internet.

If we do not foresee any practical usage of this feature of `LocalOnlyHotspot` (for my case I do not as I explained, since I cannot insert a randomly generated SSID/PSK on the IoT devices, but would need a preshared known one so they would be able to connect to the phone app) it may be just a waste of resources to it to the project I'm afraid.

**Comment by guyluz11** [comment]
Affected me when I was trying  to use `WiFiForIoTPlugin.registerWifiNetwork()` to set access point.
Got the following massage `Error updating network configuration`

Suggestion:
Adding a method to open the android/ios settings menu on opening access point could be cool.

**Comment by fedepell** [comment]
@guyluz11 : yep that should be quite possible (to be verified if it is all same depending on device), but sadly not very "advanced" compared to what we had before :-( But on the other side if the platform decided to cut such features, it's also hard to do much more...

**Comment by daadu** [comment]
@fedepell I would suggest you review changes in #126 , it does the necessary changes.

**Comment by daadu** [comment]
@guyluz11 I like your idea of opening proper "settings" page for methods that are deprecated ?

**Comment by fedepell** [comment]
@daadu I gave a fast look at #126 (will try to do a code review later in case) and indeed that looks fine to me (so we can close this issue). 

But basically what was done was to say that for Android > 29 we mostly do not support anything AP-wise and return error. Of course I'm not complaining about this (as it seems there was not much we could do due to the API change) but sadly I think that the AP side of this plugin becomes therefore of very little practical use :-( (in comparison to what we had)

**Comment by daadu** [comment]
@fedepell I got your point(that it does not have a use-case for IoT now),  but as far as I know no other plugin in pub.dev supports "hotspot" (pre or post Q), so I would want to continue that and implement the AP functionality in whatever way it is possible post Q.

If there was a plugin specifically for "hotspot" we would have discontinued ti and suggested our user to use it. Since that is not the case, we need to continue the functionality (This plugin should take that responsibility) - for other use-cases (which are non-IoT or which you and I have not thought of).

**Comment by daadu** [comment]
This feature has landed on pub.dev with [v0.3.1](https://pub.dev/packages/wifi_iot/versions/0.3.1).
