### ISSUE TITLE
Reconnect to existing Wifi Network

### ISSUE THREAD

**Issue by wheel1992** [alternadom/WiFiFlutter#22]
Hi @alternadom , does the following code reconnect to existing saved Wifi network?
```dart
...
WiFiForIoTPlugin.connect(...);
...
```

**Comment by alternadom** [comment]
Hi,

Depends on the "joinOnce" argument.. but it does if you previously set it to "true"!

**Comment by daadu** [comment]
Because of lack of documentation, joinOnce is a bit confusing. Doesn't joinOnce=true should mean that the WiFi network connected should only connect once? I also noticed that Android is remembering the network even when joinOnce is true, is that correct behaviour?

@alternadom can you please clarify it.

I am thinking of writing some docs for the APIs of this lib.

**Comment by alternadom** [comment]
Hi,
I think it is a bug but i don't know why it is happening!
It would be great to write a doc about the lib, thanks by advance for your help :)
