### ISSUE TITLE
Option to connect without scanning?

### ISSUE THREAD

**Issue by tristan2468** [alternadom/WiFiFlutter#8]
It would be nice to have a `connectTo()` method which does not first need to scan for hotspots. This would mean apps could omit the `LOCATION` permissions from their required permissions.

**Comment by alternadom** [comment]
Hi,
Yes, it would be nice indeed!
I don't have time at this period but I will keep that in mind ;)

**Comment by pboos** [comment]
Have implemented this in the following pull request: https://github.com/alternadom/WiFiFlutter/pull/12

There it still is called findAndConnect. But as well think this should be called `connectTo`. Because on iOS there is no find happening anyway.
For now the android does a find still in case there is no `security` parameter provided (security = null).
